env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
extends:
  - airbnb-typescript
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:eslint-comments/recommended'
  - 'plugin:jest/recommended'
  - 'plugin:promise/recommended'
  - prettier
  - prettier/react
  - prettier/@typescript-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
  project: ./tsconfig.json
settings:
  react:
    version: detect
plugins:
  - '@typescript-eslint'
  - eslint-comments
  - jest
  - promise
  - react
  - prettier
rules:
  prettier/prettier: 'error'
